services:
  similarproducts-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      EXTERNAL_API_BASE_URL: http://simulado:80
    depends_on:
      - simulado
    networks:
      - similarproducts-net

  simulado:
    image: ldabiralai/simulado:latest
    ports:
      - "3001:80"
    volumes:
      - ./shared/simulado:/app
    command: ./bin/simulado -f /app/mocks.json
    networks:
      - similarproducts-net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - similarproducts-net
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data:

networks:
  similarproducts-net:
    driver: bridge

